### PR TITLE
Added a `_retries` variable

### PR DESCRIPTION
**Pull request by iTaybb**
Added a `_retries` variable at the main module file (`musicbrainz.py`). Underscored so people only use if they know what they're doing.

Solved issues #174 and #218.

Signed-off-by: Itay Brandes <Brandes.Itay@gmail.com>

### CODE REVIEW

**Comment by alastair** [comment]
Cool, thanks! We'll get to this as soon as possible.

**Comment by iTaybb** [comment]
Great. Please let me know if you want any changes/fixes regarding it.

**Comment by iTaybb** [comment]
Bumping this again...

**Comment by iTaybb** [comment]
bump

**Comment by iTaybb** [comment]
bump

**Comment by alastair** [comment]
I don't know why I never merged this 🤷 I thought it needed more work but I think it's fine...
In the chance that we upgrade to requests (#273) this syntax will change anyway, but it makes sense to add this functionality for now in case anyone needs it.

**Pull request merged**
