### PR TITLE
Add work-rels as an include for recordings

### PR DESCRIPTION
**Pull request by mhendu**
In order to find a work id for an individual track (as opposed to a release) I think this update is needed.

### CODE REVIEW

**Comment by sampsyo** [comment]
Hi! Thanks for pointing this out. When discussing changes that have to do with the MusicBrainz API, it can be helpful to point to some evidence that this is the right thing. Specifically, can you find the place in the MB WS documentation that discusses the `work-rels` include? Or maybe you can demonstrate a couple of API calls (i.e., URLs under `musicbrainz.org/ws/2`) that show what happens when `work-rels` is used?

**Comment by mhendu** [comment]
From the beets thread:

I think work-level-rels is intended to be combined with other lookups to return results. See for instance:

http://musicbrainz.org/ws/2/recording/aff7db3a-b566-47ef-bb44-b11fa2a88295?inc=work-rels+artist-rels+artist-credits+work-level-rels

Now without:

http://musicbrainz.org/ws/2/recording/aff7db3a-b566-47ef-bb44-b11fa2a88295?inc=work-rels+artist-rels+artist-credits

You need artist-rels, work-rels and work-level-rels to get the composer. Omitting any one of those will return results without the composer.

**Comment by alastair** [comment]
Hi,
`work-rels` already exists as a valid include for recordings. This is populated from the `RELATION_INCLUDES` variable

```
In [2]: import musicbrainzngs
In [5]: "work-rels" in musicbrainzngs.musicbrainz.VALID_INCLUDES["recording"]
Out[5]: True
```

However, in the example that you gave, you're mentioning `work-level-rels`. This already exists both in recording and release as valid includes. Which include do you think is necessary?

**Comment by alastair** [comment]
Closing, both

    mb.get_recording_by_id("aff7db3a-b566-47ef-bb44-b11fa2a88295", includes=['work-rels', 'artist-rels', 'artist-credits', 'work-level-rels'])

and 

    mb.get_recording_by_id("aff7db3a-b566-47ef-bb44-b11fa2a88295", includes=['work-rels', 'artist-rels', 'artist-credits']) 

work and return data. It's up to the caller to know which includes to use

**Pull request closed without merging**
