### PR TITLE
Support parsing pregap tracks

### PR DESCRIPTION
**Pull request by ruippeixotog**
Musicbrainz added support for pregap tracks in mediums a few months ago. This pull request makes musicbrainzngs parse and return those tracks and would give the possibility for beets to support them too (issue [here](https://github.com/sampsyo/beets/issues/1104)).

Some releases which have pregap tracks for testing: [Sea of Cowards](http://musicbrainz.org/ws/2/release/8eb2b179-643d-3507-b64c-29fcc6745156?inc=recordings), [The Calling](http://musicbrainz.org/ws/2/release/fa2abd91-f698-4935-980b-9a7f55444899?inc=recordings).

### CODE REVIEW

**Comment by mineo** [comment]
Thanks for the pull request! Can you please follow https://github.com/alastair/python-musicbrainzngs/pull/163#issuecomment-94737258 to sign off on this commit, so we can merge it?

Also, please add at least a basic test to make sure the `pregap`-element gets parsed correctly similar to the already existing track tests in https://github.com/alastair/python-musicbrainzngs/blob/master/test/test_mbxml_release.py#L37.

This would fix one part of #154.

**Comment by ruippeixotog** [comment]
Ok, I'll add the test. Is it enough to add a new sample response with a pregap track in `test/data/release` and a test that checks if the track exists in the response and has some attributes? Something like:

```
medium = res["release"]["medium-list"][0]
self.assertTrue("pregap" in medium)
self.assertEqual("<track's title>", medium["pregap"]["title"])
self.assertEqual("<track's position>", medium["pregap"]["position"])
self.assertEqual("<track's length>", medium["pregap"]["length"])
```

**Comment by mineo** [comment]
Yes, that should be enough. I think the important part are checking that the pregap track exists and that both number and position are there (both usually being 0 or empty makes them cases for "if position:"-like code that could make them disappear).

**Comment by ruippeixotog** [comment]
Done, please check if everything's ok now :)

**Comment by mineo** [comment]
Merged, thanks!

**Pull request merged**
