### PR TITLE
Add target-credit parsing support

### PR DESCRIPTION
**Pull request by iTaybb**
Useful here, for example:
musicbrainzngs.get_artist_by_id('b3785a55-2cf6-497d-b8e3-cfa21a36f997',
includes=['artist-rels'])

### CODE REVIEW

**Comment by mineo** [comment]
This is related to #162 

Looks good to me, but please sign off on the commit (see https://github.com/alastair/python-musicbrainzngs/blob/master/CONTRIBUTING.md). Also, would you mind adding a test case for this? Just saving the XML from http://musicbrainz.org/ws/2/artist/b3785a55-2cf6-497d-b8e3-cfa21a36f997?inc=artist-rels into `test/data/artist` and adding a short test case to `test_mbxml_artist.py` would be great!

**Comment by iTaybb** [comment]
Added tests. They look fine. Should be OK now!

**Comment by iTaybb** [comment]
@mineo Any problem with the commits now?

**Comment by mineo** [comment]
Nope, looks good, thanks for pinging me and for the changes!

**Pull request merged**
