### PR TITLE
Read xml attributes and values from <attribute-list> elements

### PR DESCRIPTION
**Pull request by alastair**
Last part of #142!

Previously, with <attribute> values, we only read the text value,
however now these tags can have value="" and credited-as=""
attributes, which we now read. We add these to a separate list of
dictionaries to keep backwards compatibility with the existing
attribute-list element.

Need to add some documentation saying to now use the new element

I'm not sure about the implementation of parse_relation_attribute_element. I thought that these attributes could be anything, but looking at the mmd I see there are only two options - `value` and `credited-as` (https://bitbucket.org/metabrainz/mmd-schema/src/master/schema/musicbrainz_mmd-2.0.rng?fileviewer=file-view-default#musicbrainz_mmd-2.0.rng-2311:2317). Perhaps we could just adapt `parse_work_attribute` to support the three attributes (including `type`) and adjust it as new changes are made to mmd. The current system means we have forward compatibility, but that hasn't stopped us parsing this data strictly in the past.

I added the `attribute-dict` item to works as well, although it seems we don't have a backwards compatibility problem here, as this list has always been a dict. Should we remove `attribute-dict` then? It's strange that we have `attribute-list` appearing in two places (relations, and works), with different meanings.

The name `attribute-dict` still doesn't make me feel happy, especially that it's a list of dicts. Do we call it `attribute-dicts`? Perhaps we could just call it `attributes` - it doesn't reflect the XML as strictly as we normally follow it, but it is a lot simpler to read.

### CODE REVIEW

**Comment by JonnyJD** [comment]
First of all: I also find it really strange that the `attribute-list` from the web service works completely different for works and relations.
Example for works (*not* a relation):
http://musicbrainz.org/ws/2/work/b85845e2-38fc-3092-a992-d373e7d517e9
```
<attribute-list>
  <attribute type="Key">G-flat major</attribute>
</attribute-list>
```
Example for artist-relations (member of band):
http://musicbrainz.org/ws/2/artist/57961a97-3796-4bf7-9f02-a985a8979ae9?inc=artist-rels
```
<attribute-list>
  <attribute>founder</attribute>
</attribute-list>
```
series-relations(part of):
musicbrainz.org/ws/2/work/72c9aad2-3c95-4e3e-8a01-3974f8fef8eb?inc=series-rels+attr
```
<attribute-list>
  <attribute value="BuxWV 1">number</attribute>
</attribute-list>
```

For some relations the attribute-list isn't of much help without the value:
```
'attribute-list': ['number']
```
For others (booleans) it is (not listed when false):
```
'attribute-list': ['founder']
```
So the attribute-list is possibly even used and we really can't change how we return that.

Note that for all relation attributes the meaning is backwards like for work attributes.
For works the value is in the text and for relations the name of the attribute is in the text Oo.

Using `attributes`, rather than `attribute-dict` sounds better, but from the name it isn't clear what's the difference to `attribute-list`. Both are lists.
I would use *`attribute-dicts`* note the plural s.

Not sure about adding `attribute-dicts` to works. I probably wouldn't because that would indicate it works the same as the 'attribute-dicts` from relations, but it doesn't. 
Compare (both relations) for `number=BuxWV 1`:
```
{'value': 'BuxWV 1', 'attribute': 'number'}
```
and (work attributes) for `Key=G-flat major`
```
{'type': 'Key', 'attribute': 'G-flat major'}

```

Having `attribute-list` in two locations working differently can't be changed now. Having `attribute-dicts` in two locations working differently isn't better and we don't have to.

**Comment by alastair** [comment]
There's not much we can do about the differences between work attributes and relation attributes. I can imagine that relation attributes were done this way because it's backwards compatible with the existing system, and work attributes were done that way because it's "correct"

I agree with your comment about `attribute-dicts`, because it's plural. This is one of the reasons I was wanting to use just plain `attributes` - the `dicts` part sounds really messy. To keep backwards compatibility we need to keep `attribute-list`. My plan was to document it as being deprecated, and recommend that people use `attributes` instead (which can contain both single item attributes, and key/value attrs).

I agree also about not adding it to works, if it doesn't act differently, and it doesn't give more data.
Here's an idea though - what about using this chance to normalise the two attribute items. So in the case of 
```
<attribute-list>
  <attribute value="BuxWV 1">number</attribute>
</attribute-list>
```
we convert to 
```
{'value': 'BuxWV 1', 'key': 'number'}
```
and
```
<attribute-list>
  <attribute type="Key">G-flat major</attribute>
</attribute-list>
```
we make
```
{'type': 'Key', 'value': 'G-flat major'}
```
This means we can:
1) make the element with the name `attributes` the same in both places
2) be useful as an api wrapper and fix some of the downsides in the api

**Comment by JonnyJD** [comment]
Having `attributes` as a normalized dict sounds good.

**Comment by alastair** [comment]
I'm still struggling with a way to show all this information nicely

Considering that we have the following attribute styles

1. `<attribute credited-as="Yamaha and Steinway pianos">piano</attribute>` (recording-instrument relation)
2. `<attribute>piano</attribute>` (recording-instrument relation)
3. `<attribute>founder</attribute>` (in many places)
4. `<attribute value="BuxWV 1">number</attribute>` (work-series, and possibly other places)
5. `<attribute type="Key">G-flat major</attribute>` (our special snowflake work attributes)

We all seem to agree that work attributes is a nicer xml format, but I still don't know the best way to format the others. After re-reading my previous comment I can't make sense of it.

I agree we can format 4. and 5. as 
`number=BuxWV 1` and `Key=G-flat major`. What should a common set of dictionary keys be for this?
Does this also make sense for 1.? It definitely doesn't mean piano=Yamaha and Steinway pianos (or does it?)

To me the first 3 seem easy:
1. `{attribute: piano, credited-as: Yamaha and Steinway pianos}`
2. `{attribute: piano}`
3. `{attribute: founder}`

But the others still confuse me. If we are to always have a key 'attribute', what should it be for 4.? We could say that it's the value which changes the most:
4. `{attribute: BuxWV 1, type: number}`
but then this is the opposite of 1., which is defined in the same attribute block in the schema file. This means a lot of special casing.
5. `{attribute: G-flat major, type: key}`

This both follows the xml, and matches 4. Is that a good idea?

**Comment by kepstin** [comment]
For 4., I'd go with `{attribute: number, value: "BuxWV 1"}`, as that seems to provide the best consistency with the other attributes.

But that said, this makes 5. a bit of a pain to deal with. my preferred representation here would be `{attribute: key, value: "G-flat major"}` to be consistent with 4., but that really involves some special-casing, since the xml format is so different for that attribute.

**Comment by mwiencek** [comment]
For 4 & 5 I would suggest `{attribute: number, value: BuxWV 1}` and `{attribute: key, value: G-flat major}`.

**Comment by alastair** [comment]
thanks @kepstin and @mwiencek! The verification is just what I needed. It's not too difficult to special-case 5, since this is only used in work attributes, and it's a different codepath than all other attributes anyway.

**Pull request merged**
